In the line below, write your first and last name.

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import *

In the empty code cell below, create a 5 x 3 matrix called ***mat1*** composed of random numbers taken from a Gaussian distribution.

In [0]:
mat1 = randn(5, 3)

In the code cell below, create a 3 x 4 matrix called ***mat2*** where every element in the matrix is the value 1.

In [0]:
mat2 = np.ones([3, 4])

In the code cell below, perform a matrix multiply between ***mat1*** and ***mat2*** and call the resulting matrix mat_mul.

In [0]:
mat_mul = np.matmul(mat1, mat2)

How many rows and columns should the matrix ***mat_mul*** have? Enter your answer in the line below.

5 rows and 4 columns

Can ***mat1*** and ***mat2*** be added together, elementwise? Answer in the line below.

No, they aren't the same shapes. To do element-wise operations, the number of rows and the number of columns must be the same in both structures.

In the line below, print the value of ***mat1<sub>0,2</sub>***

In [17]:
print(mat1[0,2])

0.25395109186319736

In the line below, change the value of ***mat1<sub>2,2</sub>*** to 0.3. Then, print ***mat1*** to show the change.

In [18]:
mat1[2,2] = 0.3
print(mat1)

[[ 0.7542739  -0.66066053  0.25395109]
 [ 1.09682449  0.64067488 -0.85244542]
 [-0.14207947 -0.04624282  0.3       ]
 [-1.85962493 -0.347736    0.96230984]
 [ 0.54689093 -0.56848914  0.54425022]]

In the line below, print the shape of ***mat2***.

In [22]:
print(mat2.shape)

(3, 6)

In the line below, add a value of 2.0 to every element in ***mat2***. Then print ***mat2*** to show the result.

In [23]:
mat2 += 2.0
print(mat2)

[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]

In the line below, take the sum of each column of ***mat1*** and call the result ***mat1sum***. Then, print ***mat1sum*** and its shape.

In [25]:
mat1sum = np.sum(mat1, 0)
print(mat1sum)
print(mat1sum.shape)

[ 0.39628492 -0.98245361  1.20806573]
(3,)

In the line below, write the shape you would expect if you transposed a 8 x 3 matrix.

A matrix with shape 3 x 8.

In the line below, take the mean of ***mat1*** and call the result ***mat1mean***. Then, print ***mat1mean***.

In [27]:
mat1mean = np.mean(mat1)
print(mat1mean)

0.04145980274111897

In the line below, create a variable called ***mat1row1*** which is the first row of ***mat1***. Then, print ***mat1row1*** and its shape.

In [28]:
mat1row1 = mat1[0, :]
print(mat1row1)
print(mat1row1.shape)

[ 0.7542739  -0.66066053  0.25395109]
(3,)

In the line below, create a variable called ***mat1row2*** which is the second row of ***mat1***. Then, print ***mat1row2*** and its shape.

In [29]:
mat1row2 = mat1[1, :]
print(mat1row2)
print(mat1row2.shape)

[ 1.09682449  0.64067488 -0.85244542]
(3,)

In the line below, create a variable called ***mat1col1*** which is the first column of ***mat1***. Then, print ***mat1col1*** and its shape.

In [30]:
mat1col1 = mat1[:, 0]
print(mat1col1)
print(mat1col1.shape)

[ 0.7542739   1.09682449 -0.14207947 -1.85962493  0.54689093]
(5,)

In the line below, print the maximum value in ***mat1***, as well as the minimum value of ***mat1***.

In [31]:
print(np.amax(mat1))
print(np.amin(mat1))

1.0968244924008597
-1.859624929476598

In the line below, print the number of elements in ***mat1***.

In [32]:
print(mat1.size)

15

In the line below, create a matrix of zeros called ***mat3*** with shape 4 x 4. Then print ***mat3***.

In [37]:
mat3 = np.zeros([4, 4])
print(mat3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In the line below, create matrix of ones called ***mat4*** with shape 4 x 4. Then print ***mat4***.

In [38]:
mat4 = np.ones([4, 4])
print(mat4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In the line below, add ***mat3*** and ***mat4*** elementwise and call the resulting matrix ***mat3_4***. Then print ***mat3_4***.

In [39]:
mat3_4 = mat3 + mat4
print(mat3_4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In the line below, multiply ***mat3*** by ***mat4*** elementwise and call the resulting matrix ***mat3_4mult*** and print it.

In [40]:
mat3_4mult = mat3 * mat4
print(mat3_4mult)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In the line below, create new matrix called ***mat5*** with shape 4 x 3 with random numbers from a normal distribution. Then print ***mat5***.

In [42]:
mat5 = randn(4, 3)
print(mat5)

[[ 0.06182718  2.31288885  1.44497883]
 [-0.06118643 -0.17003236 -0.5796956 ]
 [-0.63216465 -0.29305296 -0.07465526]
 [ 0.61559284  1.41509435 -1.43554919]]

In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat4*** and ***mat5*** in that order (True or False).

True. The number of columns in ***mat4*** and the number of rows in ***mat5*** are the same.

In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat4*** and ***mat5*** if you transpose ***mat4*** (True or False).

True

In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat5*** and ***mat4*** in that order (True or False).

False. ***mat5*** has three columns, and ***mat4*** has four rows.

In the line below, transpose ***mat4*** and perform a matrix multiply between ***mat4*** and ***mat5*** in that order and call the resulting matrix ***mat45mult***. Then, print the shape of the resulting matrix.

In [43]:
mat45mult = np.matmul(mat4.transpose(), mat5)
print(mat45mult)

[[-0.01593106  3.26489787 -0.64492122]
 [-0.01593106  3.26489787 -0.64492122]
 [-0.01593106  3.26489787 -0.64492122]
 [-0.01593106  3.26489787 -0.64492122]]

To submit this assignment, click on File > Download as .ipynb and upload the downloaded notebook to the Homework1 folder on the class github.